import '../models/recipe.dart';
import '../models/fridge_item.dart';

class MockData {
  static const String defaultRegion = 'Ireland';

  static const List<String> defaultCuisines = [
    'Western & Italian',
    'Japanese',
    'Chinese & Asian Fusion',
    'Korean',
    'Quick & Easy Comfort',
  ];

  static const List<String> defaultDietaryRestrictions = [
    'Vegetarian',
  ];

  static const List<String> defaultAppliances = [
    'Air Fryer',
    'Microwave',
    'Oven',
    'Stovetop',
  ];

  static final List<Recipe> seedRecipes = [
    const Recipe(
      id: 'r1',
      title: 'Kimchi Fried Rice with Soft Egg',
      koreanTitle: '김치볶음밥',
      imageUrl: '',
      cookingTimeMinutes: 15,
      cookingMethod: 'Stovetop',
      difficulty: 'Easy',
      kitchenMatchPercent: 95,
      category: 'Cook with what you have',
      isSaved: true,
      ingredients: [
        RecipeIngredient(name: 'Aged Kimchi', amount: '1 cup', status: 'have'),
        RecipeIngredient(name: 'Cooked Jasmine Rice', amount: '2 cups', status: 'have'),
        RecipeIngredient(name: 'Egg', amount: '1 large', status: 'have'),
        RecipeIngredient(name: 'Sesame Oil', amount: '1 tbsp', status: 'have'),
        RecipeIngredient(name: 'Gochugaru (Chili Flakes)', amount: '1 tsp', status: 'low'),
      ],
      cookingSteps: [
        'Chop the kimchi into bite-sized pieces.',
        'Heat 1 tbsp oil in a pan over medium heat and sauté kimchi for 3 minutes.',
        'Add cooked rice and gochugaru, mixing thoroughly.',
        'Drizzle sesame oil around the pan edges for aroma.',
        'Fry an egg sunny-side up in a separate small pan and serve on top.',
      ],
    ),
    const Recipe(
      id: 'r2',
      title: 'Air Fryer Crispy Tofu & Soy Dip',
      koreanTitle: '두부구이',
      imageUrl: '',
      cookingTimeMinutes: 18,
      cookingMethod: 'Air Fryer',
      difficulty: 'Easy',
      kitchenMatchPercent: 88,
      category: 'Quick & Simple',
      isSaved: true,
      ingredients: [
        RecipeIngredient(name: 'Firm Tofu', amount: '300 g', status: 'have'),
        RecipeIngredient(name: 'Soy Sauce', amount: '2 tbsp', status: 'have'),
        RecipeIngredient(name: 'Cornstarch', amount: '1.5 tbsp', status: 'have'),
        RecipeIngredient(name: 'Green Onion', amount: '1 stalk', status: 'missing'),
      ],
      cookingSteps: [
        'Press tofu with paper towels and cube into 2cm blocks.',
        'Toss cubed tofu with cornstarch and a touch of oil until coated.',
        'Air fry at 200°C (390°F) for 15 minutes, shaking halfway.',
        'Whisk soy sauce, sesame oil, and chopped green onion for dipping.',
      ],
    ),
    const Recipe(
      id: 'r3',
      title: 'Honey Butter Roasted Sweet Potato',
      koreanTitle: '허니버터 고구마',
      imageUrl: '',
      cookingTimeMinutes: 25,
      cookingMethod: 'Oven',
      difficulty: 'Easy',
      kitchenMatchPercent: 100,
      category: 'Easy to find near you',
      isFavorite: true,
      ingredients: [
        RecipeIngredient(name: 'Sweet Potatoes', amount: '2 medium', status: 'have'),
        RecipeIngredient(name: 'Unsalted Butter', amount: '20 g', status: 'have'),
        RecipeIngredient(name: 'Honey', amount: '1 tbsp', status: 'have'),
      ],
      cookingSteps: [
        'Wash sweet potatoes thoroughly and slice in half lengthwise.',
        'Bake at 200°C for 20 minutes until tender.',
        'Melt butter over top and drizzle with Irish wildflower honey.',
      ],
    ),
    const Recipe(
      id: 'r4',
      title: 'Microwave Fluffy Steamed Egg',
      koreanTitle: '계란찜',
      imageUrl: '',
      cookingTimeMinutes: 5,
      cookingMethod: 'Microwave',
      difficulty: 'Easy',
      kitchenMatchPercent: 92,
      category: 'Almost there',
      ingredients: [
        RecipeIngredient(name: 'Eggs', amount: '3 large', status: 'have'),
        RecipeIngredient(name: 'Warm Water / Stock', amount: '150 ml', status: 'have'),
        RecipeIngredient(name: 'Salt & Fish Sauce', amount: '0.5 tsp', status: 'have'),
        RecipeIngredient(name: 'Sesame Seeds', amount: '1 pinch', status: 'low'),
      ],
      cookingSteps: [
        'Whisk eggs vigorously with warm water, salt, and fish sauce in a microwave-safe bowl.',
        'Cover with a lid or plate leaving a small gap for steam.',
        'Microwave at high power for 3.5 to 4 minutes until puffed and velvety.',
      ],
    ),
    const Recipe(
      id: 'r5',
      title: 'Chilled Sesame Cucumber Salad',
      koreanTitle: '오이무침',
      imageUrl: '',
      cookingTimeMinutes: 8,
      cookingMethod: 'No-cook',
      difficulty: 'Easy',
      kitchenMatchPercent: 100,
      category: 'Quick & Simple',
      ingredients: [
        RecipeIngredient(name: 'Persian Cucumber', amount: '2 small', status: 'have'),
        RecipeIngredient(name: 'Garlic', amount: '1 clove', status: 'have'),
        RecipeIngredient(name: 'Rice Vinegar', amount: '1 tbsp', status: 'have'),
        RecipeIngredient(name: 'Toasted Sesame Oil', amount: '1 tsp', status: 'have'),
      ],
      cookingSteps: [
        'Smash cucumbers gently with a rolling pin and cut into chunks.',
        'Toss with crushed garlic, rice vinegar, sesame oil, and sea salt.',
        'Chill in fridge for 5 minutes before serving.',
      ],
    ),
    const Recipe(
      id: 'r6',
      title: 'Matcha Oat Milk Iced Latte',
      koreanTitle: '말차 라떼',
      imageUrl: '',
      cookingTimeMinutes: 4,
      cookingMethod: 'No-cook',
      difficulty: 'Easy',
      kitchenMatchPercent: 100,
      category: 'Drinks',
      isFavorite: true,
      ingredients: [
        RecipeIngredient(name: 'Matcha Powder', amount: '1 tsp', status: 'have'),
        RecipeIngredient(name: 'Oat Milk', amount: '200 ml', status: 'have'),
        RecipeIngredient(name: 'Agave / Maple Syrup', amount: '1 tsp', status: 'have'),
      ],
      cookingSteps: [
        'Whisk matcha powder with 30ml warm water until frothy.',
        'Fill glass with ice cubes and oat milk.',
        'Pour matcha shot over oat milk for beautiful layered aesthetic.',
      ],
    ),
    const Recipe(
      id: 'r7',
      title: 'Korean Strawberry Milk & Shaved Ice',
      koreanTitle: '딸기 빙수',
      imageUrl: '',
      cookingTimeMinutes: 10,
      cookingMethod: 'No-cook',
      difficulty: 'Easy',
      kitchenMatchPercent: 90,
      category: 'Pastry & Dessert',
      ingredients: [
        RecipeIngredient(name: 'Fresh Strawberries', amount: '100 g', status: 'have'),
        RecipeIngredient(name: 'Whole Milk', amount: '250 ml', status: 'have'),
        RecipeIngredient(name: 'Condensed Milk', amount: '2 tbsp', status: 'have'),
      ],
      cookingSteps: [
        'Muddle strawberries with 1 tbsp sugar to make fresh puree.',
        'Shave frozen milk ice block using shaver or blender.',
        'Top milk snow with strawberry puree and drizzle with condensed milk.',
      ],
    ),
    const Recipe(
      id: 'r8',
      title: 'Pan-Seared Pork Chop with Rosemary Garlic Butter',
      koreanTitle: 'Western Gourmet',
      imageUrl: '',
      cookingTimeMinutes: 18,
      cookingMethod: 'Stovetop',
      difficulty: 'Easy',
      kitchenMatchPercent: 100,
      category: 'Western & Gourmet',
      ingredients: [
        RecipeIngredient(name: 'Pork Loin Chop', amount: '1-2 chops', status: 'have'),
        RecipeIngredient(name: 'Butter', amount: '2 tbsp', status: 'have'),
        RecipeIngredient(name: 'Garlic', amount: '2 cloves', status: 'have'),
        RecipeIngredient(name: 'Rosemary Whole', amount: '1 sprig', status: 'have'),
        RecipeIngredient(name: 'Salt', amount: '1 pinch', status: 'have'),
      ],
      cookingSteps: [
        'Pat pork chops dry with paper towel and season both sides with salt.',
        'Heat a heavy pan over medium-high heat until hot. Sear chops for 3-4 mins per side until golden.',
        'Drop in butter, crushed garlic, and whole rosemary. Baste melted foaming butter over the chops for 2 minutes.',
        'Rest chops for 5 minutes on a board before slicing.',
      ],
    ),
    const Recipe(
      id: 'r9',
      title: 'Crispy Breaded Chicken with Lemon Pan Sauce',
      koreanTitle: 'Bistro Classic',
      imageUrl: '',
      cookingTimeMinutes: 15,
      cookingMethod: 'Air Fryer',
      difficulty: 'Easy',
      kitchenMatchPercent: 100,
      category: 'Western & Gourmet',
      ingredients: [
        RecipeIngredient(name: 'Breaded Chicken Steak', amount: '1 piece', status: 'have'),
        RecipeIngredient(name: 'Lemon', amount: '0.5 piece', status: 'have'),
        RecipeIngredient(name: 'Butter', amount: '1 tbsp', status: 'have'),
        RecipeIngredient(name: 'Garlic', amount: '1 clove', status: 'have'),
      ],
      cookingSteps: [
        'Air fry breaded chicken steak at 195°C for 12-14 minutes until crisp and golden.',
        'In a small skillet, gently melt butter with minced garlic until aromatic.',
        'Squeeze fresh lemon juice into the butter to create a glossy pan sauce.',
        'Slice chicken steak and spoon lemon butter glaze over top.',
      ],
    ),
    const Recipe(
      id: 'r10',
      title: 'Garlic Butter Courgettes & Ham Noodles',
      koreanTitle: 'Italian Fusion',
      imageUrl: '',
      cookingTimeMinutes: 12,
      cookingMethod: 'Stovetop',
      difficulty: 'Easy',
      kitchenMatchPercent: 100,
      category: 'Italian & Fusion',
      ingredients: [
        RecipeIngredient(name: 'Irish Courgettes', amount: '1 medium', status: 'have'),
        RecipeIngredient(name: 'Irish Traditional Ham', amount: '50 g', status: 'have'),
        RecipeIngredient(name: 'Noodles', amount: '1 portion', status: 'have'),
        RecipeIngredient(name: 'Butter', amount: '1.5 tbsp', status: 'have'),
        RecipeIngredient(name: 'Garlic', amount: '2 cloves', status: 'have'),
        RecipeIngredient(name: 'Red Cheddar Cheese', amount: '20 g', status: 'have'),
      ],
      cookingSteps: [
        'Boil noodles until al dente, saving 3 tbsp noodle water.',
        'Slice courgettes into rounds and ribbon the ham.',
        'Melt butter in a pan with sliced garlic, sauté courgettes and ham until golden.',
        'Toss boiled noodles with reserved water, melted butter, and top with grated cheddar cheese.',
      ],
    ),
    const Recipe(
      id: 'r11',
      title: 'Lao Gan Ma Chili Crisp Fried Noodles',
      koreanTitle: 'Sichuan Bistro',
      imageUrl: '',
      cookingTimeMinutes: 10,
      cookingMethod: 'Stovetop',
      difficulty: 'Easy',
      kitchenMatchPercent: 100,
      category: 'Asian Fusion',
      ingredients: [
        RecipeIngredient(name: 'Noodles', amount: '1 portion', status: 'have'),
        RecipeIngredient(name: '老干妈 (Lao Gan Ma)', amount: '1 tbsp', status: 'have'),
        RecipeIngredient(name: 'Garlic', amount: '2 cloves', status: 'have'),
        RecipeIngredient(name: 'Soy Sauce', amount: '1 tbsp', status: 'have'),
        RecipeIngredient(name: 'Dark Soy Sauce', amount: '0.5 tsp', status: 'have'),
      ],
      cookingSteps: [
        'Cook noodles, drain, and rinse briefly with cold water.',
        'Sauté minced garlic in a wok or skillet over medium heat.',
        'Add Lao Gan Ma chili crisp, soy sauce, and dark soy sauce until fragrant.',
        'Toss in cooked noodles over high heat until glossy and coated evenly.',
      ],
    ),
    const Recipe(
      id: 'r12',
      title: 'White Miso & Dried Kelp Dashi Broth',
      koreanTitle: 'Japanese Home Style',
      imageUrl: '',
      cookingTimeMinutes: 10,
      cookingMethod: 'Stovetop',
      difficulty: 'Easy',
      kitchenMatchPercent: 100,
      category: 'Japanese',
      ingredients: [
        RecipeIngredient(name: 'White Miso Paste', amount: '1.5 tbsp', status: 'have'),
        RecipeIngredient(name: 'Dried Kelp', amount: '1 piece (5cm)', status: 'have'),
        RecipeIngredient(name: 'Meehun', amount: '1 bundle', status: 'have'),
        RecipeIngredient(name: 'Garlic', amount: '1 clove', status: 'have'),
      ],
      cookingSteps: [
        'Simmer dried kelp in 450ml water for 6 minutes to extract umami dashi broth.',
        'Remove kelp piece, turn off heat, and dissolve white miso paste using a strainer or ladle.',
        'Cook meehun separately or simmer directly in broth for 2 minutes.',
        'Ladle piping hot miso dashi soup over noodles and enjoy warm.',
      ],
    ),
    const Recipe(
      id: 'r13',
      title: 'Irish Ham & Melted Cheddar Jalapeño Toast',
      koreanTitle: 'Cafe Comfort',
      imageUrl: '',
      cookingTimeMinutes: 8,
      cookingMethod: 'Air Fryer',
      difficulty: 'Easy',
      kitchenMatchPercent: 100,
      category: 'Quick & Comfort',
      ingredients: [
        RecipeIngredient(name: 'Irish Traditional Ham', amount: '2-3 slices', status: 'have'),
        RecipeIngredient(name: 'Red Cheddar Cheese', amount: '40 g', status: 'have'),
        RecipeIngredient(name: 'Sliced Green Jalapeños', amount: '1 tbsp', status: 'have'),
        RecipeIngredient(name: 'Butter', amount: '1 tbsp', status: 'have'),
      ],
      cookingSteps: [
        'Butter bread or toast on both sides.',
        'Layer thick slices of Irish traditional ham and sharp red cheddar.',
        'Top with sliced pickled green jalapeños for acidity and heat balance.',
        'Air fry at 190°C for 5-6 minutes until cheese is molten and bubbling with crisp edges.',
      ],
    ),
  ];

  static final List<Recipe> extendedMinimalistRecipes = [
    const Recipe(
      id: 'min_1',
      title: 'Soy Sauce Butter Egg Rice',
      koreanTitle: '간장계란밥',
      imageUrl: '',
      cookingTimeMinutes: 5,
      cookingMethod: 'Stovetop',
      difficulty: 'Easy',
      kitchenMatchPercent: 100,
      category: 'Cook with what you have',
      ingredients: [
        RecipeIngredient(name: 'Cooked Jasmine Rice', amount: '1 bowl', status: 'have'),
        RecipeIngredient(name: 'Egg', amount: '1 large', status: 'have'),
        RecipeIngredient(name: 'Butter', amount: '1 tbsp', status: 'have'),
        RecipeIngredient(name: 'Soy Sauce', amount: '1 tbsp', status: 'have'),
      ],
      cookingSteps: [
        'Scoop hot cooked rice into a bowl.',
        'Melt a pat of butter into the hot rice.',
        'Fry an egg sunny-side up in a small skillet.',
        'Place egg on rice, drizzle with soy sauce, and break the yolk to mix.',
      ],
    ),
    const Recipe(
      id: 'min_2',
      title: 'Dubu Kimchi Skillet',
      koreanTitle: '두부김치',
      imageUrl: '',
      cookingTimeMinutes: 10,
      cookingMethod: 'Stovetop',
      difficulty: 'Easy',
      kitchenMatchPercent: 100,
      category: 'Cook with what you have',
      ingredients: [
        RecipeIngredient(name: 'Firm Tofu', amount: '300 g', status: 'have'),
        RecipeIngredient(name: 'Aged Kimchi', amount: '1 cup', status: 'have'),
        RecipeIngredient(name: 'Sesame Oil', amount: '1 tbsp', status: 'have'),
      ],
      cookingSteps: [
        'Slice firm tofu into thick bite-sized slabs.',
        'Warm tofu gently in simmering water or pan-sear lightly.',
        'Stir-fry aged kimchi with sesame oil until fragrant and caramelized.',
        'Serve warm tofu alongside the sautéed kimchi.',
      ],
    ),
    const Recipe(
      id: 'min_3',
      title: 'Crispy Pan-Fried Dumplings',
      koreanTitle: '군만두',
      imageUrl: '',
      cookingTimeMinutes: 8,
      cookingMethod: 'Stovetop',
      difficulty: 'Easy',
      kitchenMatchPercent: 100,
      category: 'Cook with what you have',
      ingredients: [
        RecipeIngredient(name: 'Frozen Dumplings', amount: '8 pieces', status: 'have'),
        RecipeIngredient(name: 'Cooking Oil', amount: '1 tbsp', status: 'have'),
        RecipeIngredient(name: 'Soy Sauce', amount: '1 tbsp', status: 'have'),
      ],
      cookingSteps: [
        'Heat cooking oil in a flat nonstick skillet over medium-high heat.',
        'Arrange frozen dumplings in a pan and sear bottoms until golden (2 mins).',
        'Add 3 tbsp water, immediately cover with lid, and steam for 5 minutes.',
        'Uncover, let moisture evaporate until bottoms turn extra crispy, and dip in soy sauce.',
      ],
    ),
    const Recipe(
      id: 'min_4',
      title: 'Crispy Grated Potato Pancake',
      koreanTitle: '감자전',
      imageUrl: '',
      cookingTimeMinutes: 12,
      cookingMethod: 'Stovetop',
      difficulty: 'Easy',
      kitchenMatchPercent: 100,
      category: 'Quick & Simple',
      ingredients: [
        RecipeIngredient(name: 'Potatoes', amount: '2 medium', status: 'have'),
        RecipeIngredient(name: 'Salt', amount: '0.5 tsp', status: 'have'),
        RecipeIngredient(name: 'Cooking Oil', amount: '2 tbsp', status: 'have'),
      ],
      cookingSteps: [
        'Peel and grate potatoes finely into a bowl.',
        'Drain excess liquid gently and fold in salt.',
        'Heat oil in a skillet and spread potato batter into thin rounds.',
        'Pan-fry on medium heat until golden and crunchy on both sides.',
      ],
    ),
    const Recipe(
      id: 'min_5',
      title: 'Tuna Mayo Rice Bowl',
      koreanTitle: '참치마요덮밥',
      imageUrl: '',
      cookingTimeMinutes: 5,
      cookingMethod: 'No-cook',
      difficulty: 'Easy',
      kitchenMatchPercent: 100,
      category: 'Quick & Simple',
      ingredients: [
        RecipeIngredient(name: 'Canned Tuna', amount: '1 can (150g)', status: 'have'),
        RecipeIngredient(name: 'Cooked Jasmine Rice', amount: '1 bowl', status: 'have'),
        RecipeIngredient(name: 'Mayonnaise', amount: '2 tbsp', status: 'have'),
        RecipeIngredient(name: 'Soy Sauce', amount: '1 tsp', status: 'have'),
      ],
      cookingSteps: [
        'Drain liquid from canned tuna and flake gently with a fork.',
        'Mix tuna with mayonnaise and a touch of soy sauce.',
        'Warm cooked jasmine rice in a serving bowl.',
        'Spoon seasoned tuna over the rice and mix together.',
      ],
    ),
    const Recipe(
      id: 'min_6',
      title: 'Quick Gochujang Butter Noodles',
      koreanTitle: '고추장 비빔면',
      imageUrl: '',
      cookingTimeMinutes: 8,
      cookingMethod: 'Stovetop',
      difficulty: 'Easy',
      kitchenMatchPercent: 100,
      category: 'Cook with what you have',
      ingredients: [
        RecipeIngredient(name: 'Noodles', amount: '1 portion', status: 'have'),
        RecipeIngredient(name: 'Gochujang Paste', amount: '1 tbsp', status: 'have'),
        RecipeIngredient(name: 'Butter', amount: '1 tbsp', status: 'have'),
        RecipeIngredient(name: 'Soy Sauce', amount: '1 tsp', status: 'have'),
      ],
      cookingSteps: [
        'Boil noodles according to package directions, then drain.',
        'In the warm pot, melt 1 tbsp butter with gochujang paste and soy sauce.',
        'Toss warm noodles until glossy and evenly coated in the rich spicy sauce.',
      ],
    ),
    const Recipe(
      id: 'min_7',
      title: 'Braised Garlic Tofu',
      koreanTitle: '두부조림',
      imageUrl: '',
      cookingTimeMinutes: 10,
      cookingMethod: 'Stovetop',
      difficulty: 'Easy',
      kitchenMatchPercent: 100,
      category: 'Cook with what you have',
      ingredients: [
        RecipeIngredient(name: 'Firm Tofu', amount: '300 g', status: 'have'),
        RecipeIngredient(name: 'Soy Sauce', amount: '2 tbsp', status: 'have'),
        RecipeIngredient(name: 'Garlic', amount: '2 cloves', status: 'have'),
        RecipeIngredient(name: 'Sesame Oil', amount: '1 tsp', status: 'have'),
      ],
      cookingSteps: [
        'Cut firm tofu into rectangles and pat dry with paper towels.',
        'Pan-fry both sides in a skillet until light golden brown.',
        'Mix soy sauce, minced garlic, 2 tbsp water, and sesame oil.',
        'Pour sauce over tofu and simmer gently for 3 minutes until absorbed.',
      ],
    ),
    const Recipe(
      id: 'min_8',
      title: 'Steamed Sweet Potato with Butter',
      koreanTitle: '군고구마',
      imageUrl: '',
      cookingTimeMinutes: 10,
      cookingMethod: 'Microwave',
      difficulty: 'Easy',
      kitchenMatchPercent: 100,
      category: 'Quick & Simple',
      ingredients: [
        RecipeIngredient(name: 'Sweet Potatoes', amount: '2 small', status: 'have'),
        RecipeIngredient(name: 'Butter', amount: '15 g', status: 'have'),
        RecipeIngredient(name: 'Honey', amount: '1 tsp', status: 'have'),
      ],
      cookingSteps: [
        'Prick sweet potatoes with a fork and microwave for 6-8 minutes until tender.',
        'Slice open lengthwise while steaming hot.',
        'Tuck in cold butter and a gentle drizzle of honey to melt inside.',
      ],
    ),
    const Recipe(
      id: 'min_9',
      title: 'Clear Egg Drop Soup',
      koreanTitle: '계란국',
      imageUrl: '',
      cookingTimeMinutes: 7,
      cookingMethod: 'Stovetop',
      difficulty: 'Easy',
      kitchenMatchPercent: 100,
      category: 'Cook with what you have',
      ingredients: [
        RecipeIngredient(name: 'Eggs', amount: '2 large', status: 'have'),
        RecipeIngredient(name: 'Green Onion', amount: '1 stalk', status: 'have'),
        RecipeIngredient(name: 'Soy Sauce', amount: '1 tbsp', status: 'have'),
        RecipeIngredient(name: 'Sesame Oil', amount: '0.5 tsp', status: 'have'),
      ],
      cookingSteps: [
        'Bring 400ml water to a boil with 1 tbsp soy sauce.',
        'Whisk eggs lightly in a small bowl.',
        'Pour egg swirl gently into boiling broth in a circle; do not stir for 20 seconds.',
        'Turn off heat, add chopped green onion and a dash of sesame oil.',
      ],
    ),
    const Recipe(
      id: 'min_10',
      title: 'Honey Butter Cafe Toast',
      koreanTitle: '허니버터 브레드',
      imageUrl: '',
      cookingTimeMinutes: 8,
      cookingMethod: 'Oven',
      difficulty: 'Easy',
      kitchenMatchPercent: 100,
      category: 'Dessert',
      ingredients: [
        RecipeIngredient(name: 'Thick Bread / Toast', amount: '1 thick slice', status: 'have'),
        RecipeIngredient(name: 'Butter', amount: '2 tbsp', status: 'have'),
        RecipeIngredient(name: 'Honey', amount: '1.5 tbsp', status: 'have'),
        RecipeIngredient(name: 'Sugar or Cinnamon', amount: '1 pinch', status: 'have'),
      ],
      cookingSteps: [
        'Score thick bread into crosswise cubes, without cutting all the way through.',
        'Melt butter with honey and spoon generously between the crevices.',
        'Bake in oven or air fryer at 190°C for 6-8 minutes until golden and caramelized at the edges.',
        'Dust with a pinch of cinnamon or sugar and serve warm.',
      ],
    ),
    const Recipe(
      id: 'min_11',
      title: '3-Ingredient Butter Shortbread Cookies',
      koreanTitle: '버터 쿠키',
      imageUrl: '',
      cookingTimeMinutes: 15,
      cookingMethod: 'Oven',
      difficulty: 'Easy',
      kitchenMatchPercent: 100,
      category: 'Pastry',
      ingredients: [
        RecipeIngredient(name: 'Flour', amount: '1 cup (120g)', status: 'have'),
        RecipeIngredient(name: 'Butter (softened)', amount: '70 g', status: 'have'),
        RecipeIngredient(name: 'Sugar', amount: '3 tbsp', status: 'have'),
      ],
      cookingSteps: [
        'Cream softened butter and sugar together in a bowl until pale and fluffy.',
        'Fold in flour until a soft, crumbly dough forms, then press into small discs.',
        'Arrange on baking paper and prick tops gently with a fork.',
        'Bake at 170°C (340°F) for 12-14 minutes until pale golden.',
      ],
    ),
    const Recipe(
      id: 'min_12',
      title: 'Air Fryer Baked Cinnamon Apples',
      koreanTitle: '구운 시나몬 사과',
      imageUrl: '',
      cookingTimeMinutes: 10,
      cookingMethod: 'Air Fryer',
      difficulty: 'Easy',
      kitchenMatchPercent: 100,
      category: 'Dessert',
      ingredients: [
        RecipeIngredient(name: 'Apple', amount: '1 medium', status: 'have'),
        RecipeIngredient(name: 'Butter', amount: '1 tbsp', status: 'have'),
        RecipeIngredient(name: 'Honey', amount: '1 tbsp', status: 'have'),
      ],
      cookingSteps: [
        'Slice apple into wedges or rings.',
        'Toss with melted butter, honey, and an optional dash of cinnamon.',
        'Air fry at 180°C for 8-10 minutes until tender, fragrant, and slightly caramelized.',
      ],
    ),
    const Recipe(
      id: 'min_13',
      title: 'Quick Chocolate Mug Cake',
      koreanTitle: '초코 머그케이크',
      imageUrl: '',
      cookingTimeMinutes: 4,
      cookingMethod: 'Microwave',
      difficulty: 'Easy',
      kitchenMatchPercent: 100,
      category: 'Dessert',
      ingredients: [
        RecipeIngredient(name: 'Flour', amount: '3 tbsp', status: 'have'),
        RecipeIngredient(name: 'Sugar', amount: '2 tbsp', status: 'have'),
        RecipeIngredient(name: 'Milk', amount: '3 tbsp', status: 'have'),
        RecipeIngredient(name: 'Butter (melted)', amount: '1 tbsp', status: 'have'),
      ],
      cookingSteps: [
        'Whisk flour, sugar, melted butter, and milk directly inside a microwave-safe ceramic mug.',
        'Microwave at high power for 70 to 80 seconds until risen and fluffy.',
        'Let rest for 1 minute before enjoying warm.',
      ],
    ),
    const Recipe(
      id: 'min_14',
      title: 'Air Fryer Cheesy Garlic Toast',
      koreanTitle: '마늘 치즈 토스트',
      imageUrl: '',
      cookingTimeMinutes: 6,
      cookingMethod: 'Air Fryer',
      difficulty: 'Easy',
      kitchenMatchPercent: 100,
      category: 'Baking',
      ingredients: [
        RecipeIngredient(name: 'Bread / Toast', amount: '2 slices', status: 'have'),
        RecipeIngredient(name: 'Butter', amount: '1.5 tbsp', status: 'have'),
        RecipeIngredient(name: 'Garlic', amount: '1 clove', status: 'have'),
        RecipeIngredient(name: 'Cheese', amount: '30 g', status: 'have'),
      ],
      cookingSteps: [
        'Mix softened butter with minced garlic and a pinch of salt.',
        'Spread garlic butter generously over bread slices and top with cheese.',
        'Air fry or bake at 185°C for 5-6 minutes until bubbling, golden, and crispy.',
      ],
    ),
    const Recipe(
      id: 'min_15',
      title: 'Korean Corn Cheese Skillet',
      koreanTitle: '콘치즈',
      imageUrl: '',
      cookingTimeMinutes: 8,
      cookingMethod: 'Stovetop',
      difficulty: 'Easy',
      kitchenMatchPercent: 100,
      category: 'Snack & Craving',
      ingredients: [
        RecipeIngredient(name: 'Sweet Corn', amount: '1 can (180g)', status: 'have'),
        RecipeIngredient(name: 'Mayonnaise', amount: '1.5 tbsp', status: 'have'),
        RecipeIngredient(name: 'Butter', amount: '1 tbsp', status: 'have'),
        RecipeIngredient(name: 'Mozzarella / Cheese', amount: '40 g', status: 'have'),
      ],
      cookingSteps: [
        'Drain sweet corn thoroughly and toss with mayonnaise and a dash of sugar.',
        'Melt butter in a small skillet over medium heat and spread the corn evenly.',
        'Cover top with shredded cheese, put a lid on for 3-4 minutes until cheese melts and pulls stretchy.',
      ],
    ),
    const Recipe(
      id: 'min_16',
      title: 'Caramelized Honey Butter Bananas',
      koreanTitle: '바나나 구이',
      imageUrl: '',
      cookingTimeMinutes: 5,
      cookingMethod: 'Stovetop',
      difficulty: 'Easy',
      kitchenMatchPercent: 100,
      category: 'Dessert',
      ingredients: [
        RecipeIngredient(name: 'Banana', amount: '1 ripe', status: 'have'),
        RecipeIngredient(name: 'Butter', amount: '1 tbsp', status: 'have'),
        RecipeIngredient(name: 'Honey', amount: '1 tbsp', status: 'have'),
        RecipeIngredient(name: 'Cinnamon', amount: '1 pinch', status: 'have'),
      ],
      cookingSteps: [
        'Peel banana and slice into thick coins or halves.',
        'Melt butter in a pan over medium heat, add honey, and swirl together.',
        'Sear banana slices for 2 minutes on each side until deeply golden and caramelized.',
        'Dust with cinnamon and enjoy warm as a cozy dessert.',
      ],
    ),
  ];

  static final List<Recipe> simpleClassicRecipes = [
    const Recipe(
      id: 'classic_1',
      title: 'Garlic Butter Pan-Seared Chicken Thighs',
      koreanTitle: '마늘버터 닭구이',
      imageUrl: '',
      cookingTimeMinutes: 15,
      cookingMethod: 'Stovetop',
      difficulty: 'Easy',
      kitchenMatchPercent: 75,
      category: 'Everyday Classic',
      recipeSlot: 'simple_classic',
      inspirationNote: 'Golden crispy skin basted with foaming garlic butter',
      ingredients: [
        RecipeIngredient(name: 'Chicken Thighs', amount: '2-3 boneless', status: 'have'),
        RecipeIngredient(name: 'Butter', amount: '2 tbsp', status: 'have'),
        RecipeIngredient(name: 'Garlic', amount: '4 cloves (smashed)', status: 'have'),
        RecipeIngredient(name: 'Black Pepper', amount: '½ tsp', status: 'have'),
      ],
      cookingSteps: [
        'Pat chicken thighs dry with paper towel; season both sides generously with salt and cracked pepper.',
        'Lay skin-side down in a hot skillet over medium-high heat for 6-7 minutes until the skin is deep golden and crisp.',
        'Flip, drop in butter and smashed garlic cloves. Tilt skillet and spoon foaming butter over chicken for 3 minutes until cooked through.',
      ],
    ),
    const Recipe(
      id: 'classic_2',
      title: 'Sweet Soy Charred Beef Skewers',
      koreanTitle: '소고기 꼬치구이',
      imageUrl: '',
      cookingTimeMinutes: 15,
      cookingMethod: 'Stovetop',
      difficulty: 'Easy',
      kitchenMatchPercent: 70,
      category: 'Everyday Classic',
      recipeSlot: 'simple_classic',
      inspirationNote: 'Smoky, caramelized sweet soy glaze over tender charred beef',
      ingredients: [
        RecipeIngredient(name: 'Beef Steak', amount: '250g (cubed)', status: 'have'),
        RecipeIngredient(name: 'Soy Sauce', amount: '2 tbsp', status: 'have'),
        RecipeIngredient(name: 'Sugar', amount: '1 tbsp', status: 'have'),
        RecipeIngredient(name: 'Garlic', amount: '2 cloves (minced)', status: 'have'),
      ],
      cookingSteps: [
        'Whisk soy sauce, sugar, and minced garlic in a bowl; toss beef cubes to coat for 10-15 minutes.',
        'Thread marinated beef onto skewers tightly.',
        'Sear in a smoking hot pan or grill for 2 minutes per side until charred on edges and tender inside.',
      ],
    ),
    const Recipe(
      id: 'classic_3',
      title: 'Cast-Iron Basted Ribeye Steak',
      koreanTitle: '버터 아로제 스테이크',
      imageUrl: '',
      cookingTimeMinutes: 12,
      cookingMethod: 'Stovetop',
      difficulty: 'Medium',
      kitchenMatchPercent: 60,
      category: 'Everyday Classic',
      recipeSlot: 'simple_classic',
      inspirationNote: 'Deep mahogany crust, juicy center, basted with herb butter',
      ingredients: [
        RecipeIngredient(name: 'Beef Steak', amount: '1 thick cut (300g)', status: 'have'),
        RecipeIngredient(name: 'Butter', amount: '2 tbsp', status: 'have'),
        RecipeIngredient(name: 'Garlic', amount: '3 cloves (crushed)', status: 'have'),
        RecipeIngredient(name: 'Rosemary Whole', amount: '2 sprigs', status: 'have'),
        RecipeIngredient(name: 'Black Pepper', amount: '½ tsp', status: 'have'),
      ],
      cookingSteps: [
        'Bring steak to room temperature 15 mins before cooking; pat thoroughly dry and season generously with salt and pepper.',
        'Sear in a smoking hot skillet for 2 minutes undisturbed to form an intense dark crust.',
        'Flip, immediately add butter, crushed garlic, and rosemary. Tilt pan and continuously baste foaming butter over steak for 2 minutes.',
        'Rest on a board for 5 full minutes before slicing to lock in all juices.',
      ],
    ),
    const Recipe(
      id: 'classic_4',
      title: 'Crispy Oven-Roasted Pork Belly Slices',
      koreanTitle: '통삼겹 오븐구이',
      imageUrl: '',
      cookingTimeMinutes: 25,
      cookingMethod: 'Oven',
      difficulty: 'Easy',
      kitchenMatchPercent: 60,
      category: 'Everyday Classic',
      recipeSlot: 'simple_classic',
      inspirationNote: 'Crispy blistered crackling with juicy, melt-in-your-mouth pork',
      ingredients: [
        RecipeIngredient(name: 'Pork Loin Chop', amount: '300g (sliced)', status: 'have'),
        RecipeIngredient(name: 'Garlic', amount: '3 cloves (sliced)', status: 'have'),
        RecipeIngredient(name: 'Soy Sauce', amount: '1 tbsp', status: 'have'),
        RecipeIngredient(name: 'Black Pepper', amount: '½ tsp', status: 'have'),
      ],
      cookingSteps: [
        'Lightly score pork slices; season meat side with soy sauce and black pepper, keeping the outer edges dry.',
        'Rub a pinch of coarse salt onto the edges for maximum crunch.',
        'Roast at 200°C (400°F) in oven or air fryer for 20-25 minutes until fat renders and edges are blistered and crunchy.',
      ],
    ),
    const Recipe(
      id: 'classic_5',
      title: 'Pan-Seared Honey Soy Glazed Salmon',
      koreanTitle: '꿀간장 연어스테이크',
      imageUrl: '',
      cookingTimeMinutes: 12,
      cookingMethod: 'Stovetop',
      difficulty: 'Easy',
      kitchenMatchPercent: 65,
      category: 'Everyday Classic',
      recipeSlot: 'simple_classic',
      inspirationNote: 'Flaky tender salmon coated in a bubbling, glossy honey-soy reduction',
      ingredients: [
        RecipeIngredient(name: 'Salmon Fillet', amount: '1-2 fillets (200g)', status: 'have'),
        RecipeIngredient(name: 'Soy Sauce', amount: '1.5 tbsp', status: 'have'),
        RecipeIngredient(name: 'Sugar', amount: '1 tbsp', status: 'have'),
        RecipeIngredient(name: 'Butter', amount: '1 tbsp', status: 'have'),
        RecipeIngredient(name: 'Garlic', amount: '2 cloves (minced)', status: 'have'),
      ],
      cookingSteps: [
        'Season salmon lightly with salt; whisk soy sauce, sugar, and garlic in a small ramekin.',
        'Sear salmon skin-side down in a hot pan with a drizzle of oil for 4 minutes until golden.',
        'Flip, reduce heat to low, add butter and the soy glaze; swirl for 2 minutes as sauce bubbles into a sticky coating.',
      ],
    ),
    const Recipe(
      id: 'classic_6',
      title: 'Wok-Style Scallion Egg Fried Rice',
      koreanTitle: '파계란 볶음밥',
      imageUrl: '',
      cookingTimeMinutes: 10,
      cookingMethod: 'Stovetop',
      difficulty: 'Easy',
      kitchenMatchPercent: 80,
      category: 'Everyday Classic',
      recipeSlot: 'simple_classic',
      inspirationNote: 'Fluffy separated rice tossed in fragrant toasted scallion oil',
      ingredients: [
        RecipeIngredient(name: 'Rice', amount: '2 cups (cold/cooked)', status: 'have'),
        RecipeIngredient(name: 'Egg', amount: '2 large', status: 'have'),
        RecipeIngredient(name: 'Soy Sauce', amount: '1 tbsp', status: 'have'),
        RecipeIngredient(name: 'Butter', amount: '1 tbsp', status: 'have'),
      ],
      cookingSteps: [
        'Heat a skillet over high heat with butter and pour in beaten eggs; scramble vigorously for 15 seconds to create soft curds.',
        'Add cold cooked rice, breaking up clumps with spatula over high heat.',
        'Drizzle soy sauce along the scorching rim of the pan so it toasts for smoky wok aroma; toss briskly and serve.',
      ],
    ),
    const Recipe(
      id: 'classic_7',
      title: 'Oven Soy-Garlic Glazed Chicken Drumsticks',
      koreanTitle: '간장마늘 닭봉구이',
      imageUrl: '',
      cookingTimeMinutes: 25,
      cookingMethod: 'Oven',
      difficulty: 'Easy',
      kitchenMatchPercent: 70,
      category: 'Everyday Classic',
      recipeSlot: 'simple_classic',
      inspirationNote: 'Deeply savory and sticky sweet glaze roasted right to the bone',
      ingredients: [
        RecipeIngredient(name: 'Chicken Thighs', amount: '4-5 pieces', status: 'have'),
        RecipeIngredient(name: 'Soy Sauce', amount: '2 tbsp', status: 'have'),
        RecipeIngredient(name: 'Sugar', amount: '1 tbsp', status: 'have'),
        RecipeIngredient(name: 'Garlic', amount: '4 cloves (minced)', status: 'have'),
        RecipeIngredient(name: 'Black Pepper', amount: '½ tsp', status: 'have'),
      ],
      cookingSteps: [
        'Make 2 shallow slits across chicken pieces to let heat and seasoning penetrate deep to the bone.',
        'Toss with soy sauce, sugar, minced garlic, and black pepper.',
        'Bake at 200°C (400°F) for 25 minutes, brushing with pan juices halfway through, until deeply caramelized.',
      ],
    ),
    const Recipe(
      id: 'classic_8',
      title: 'Charred Lemon Herb Chicken Skewers',
      koreanTitle: '레몬 허브 치킨 꼬치',
      imageUrl: '',
      cookingTimeMinutes: 15,
      cookingMethod: 'Stovetop',
      difficulty: 'Easy',
      kitchenMatchPercent: 65,
      category: 'Everyday Classic',
      recipeSlot: 'simple_classic',
      inspirationNote: 'Bright citrus and fragrant herbs charred over sizzling heat',
      ingredients: [
        RecipeIngredient(name: 'Breaded Chicken Steak', amount: '250g (cubed)', status: 'have'),
        RecipeIngredient(name: 'Lemon', amount: '½ pc (juiced)', status: 'have'),
        RecipeIngredient(name: 'Butter', amount: '1 tbsp (melted)', status: 'have'),
        RecipeIngredient(name: 'Garlic', amount: '2 cloves (minced)', status: 'have'),
        RecipeIngredient(name: 'Rosemary Whole', amount: '1 sprig (chopped)', status: 'have'),
      ],
      cookingSteps: [
        'Toss chicken cubes with fresh lemon juice, melted butter, minced garlic, rosemary, and a pinch of salt.',
        'Thread onto skewers tightly.',
        'Sear in a smoking hot pan for 6-8 minutes, turning frequently until nicely charred on all edges and juicy inside.',
      ],
    ),
  ];

  static const List<Recipe> discoveryCatalog = [
    Recipe(
      id: 'disc_1',
      title: 'Garlic Butter Herb Prawn Fettuccine',
      koreanTitle: '갈릭 버터 새우 파스타',
      imageUrl: '',
      cookingTimeMinutes: 15,
      cookingMethod: 'Stovetop',
      difficulty: 'Easy',
      kitchenMatchPercent: 95,
      category: 'Italian Bistro',
      ingredients: [
        RecipeIngredient(name: 'Fettuccine / Noodles', amount: '1 portion (100g)', status: 'have'),
        RecipeIngredient(name: 'Prawns / Shrimp', amount: '6-8 large', status: 'have'),
        RecipeIngredient(name: 'Butter', amount: '2 tbsp', status: 'have'),
        RecipeIngredient(name: 'Garlic', amount: '3 cloves (minced)', status: 'have'),
        RecipeIngredient(name: 'Kosher Salt & Black Pepper', amount: '½ tsp each', status: 'have'),
        RecipeIngredient(name: 'Fresh Lemon Juice', amount: '1 tbsp', status: 'have'),
      ],
      cookingSteps: [
        'Boil pasta in salted boiling water until al dente; reserve ¼ cup pasta water.',
        'Melt butter with a drizzle of olive oil in a skillet over medium heat; sauté minced garlic until fragrant.',
        'Add prawns seasoned with salt and black pepper; sear 1.5 minutes per side until pink and curled.',
        'Toss boiled pasta, reserved pasta water, and lemon juice with the garlic butter emulsion until glossy and coated.',
      ],
    ),
    Recipe(
      id: 'disc_2',
      title: 'Crispy Chicken Katsu Sando with Kewpie Slaw',
      koreanTitle: '치킨 카츠 산도',
      imageUrl: '',
      cookingTimeMinutes: 18,
      cookingMethod: 'Air Fryer',
      difficulty: 'Medium',
      kitchenMatchPercent: 90,
      category: 'Japanese Cafe',
      ingredients: [
        RecipeIngredient(name: 'Chicken Breast / Fillet', amount: '1 piece', status: 'have'),
        RecipeIngredient(name: 'Brioche or White Bread', amount: '2 thick slices', status: 'have'),
        RecipeIngredient(name: 'Butter', amount: '1 tbsp', status: 'have'),
        RecipeIngredient(name: 'Shredded Cabbage', amount: '½ cup', status: 'have'),
        RecipeIngredient(name: 'Mayonnaise & Tonkatsu Sauce', amount: '1.5 tbsp each', status: 'have'),
        RecipeIngredient(name: 'Salt & Pepper', amount: '¼ tsp', status: 'have'),
      ],
      cookingSteps: [
        'Season chicken fillet with salt and pepper, lightly coat in panko or breadcrumbs.',
        'Air fry at 195°C (385°F) for 12-14 minutes until golden, crunchy, and cooked through.',
        'Toast bread slices in a pan with foaming butter until crisp.',
        'Toss shredded cabbage with mayo; assemble sando with tonkatsu sauce, crunchy chicken katsu, and slice in half.',
      ],
    ),
    Recipe(
      id: 'disc_3',
      title: 'Smoky Chipotle Cheddar & Ham Quesadilla',
      koreanTitle: '치폴레 햄 퀘사디아',
      imageUrl: '',
      cookingTimeMinutes: 10,
      cookingMethod: 'Stovetop',
      difficulty: 'Easy',
      kitchenMatchPercent: 95,
      category: 'Mexican Bistro',
      ingredients: [
        RecipeIngredient(name: 'Flour Tortilla or Flatbread', amount: '2 pieces', status: 'have'),
        RecipeIngredient(name: 'Red Cheddar Cheese', amount: '60 g (shredded)', status: 'have'),
        RecipeIngredient(name: 'Irish Traditional Ham', amount: '3 slices', status: 'have'),
        RecipeIngredient(name: 'Pickled Jalapeños', amount: '1 tbsp', status: 'have'),
        RecipeIngredient(name: 'Butter', amount: '1 tbsp', status: 'have'),
      ],
      cookingSteps: [
        'Melt half the butter in a flat skillet over medium heat and lay down one tortilla.',
        'Layer shredded red cheddar, ham slices, and chopped pickled jalapeños across the base.',
        'Top with second tortilla; cook 3-4 minutes until golden and crisp underneath.',
        'Flip carefully, adding remaining butter, and toast until cheese is completely molten and bubbling.',
      ],
    ),
    Recipe(
      id: 'disc_4',
      title: 'Creamy Tuscan Garlic & Sun-Dried Tomato Chicken',
      koreanTitle: '토스카나 치킨',
      imageUrl: '',
      cookingTimeMinutes: 20,
      cookingMethod: 'Stovetop',
      difficulty: 'Medium',
      kitchenMatchPercent: 90,
      category: 'Italian Bistro',
      ingredients: [
        RecipeIngredient(name: 'Chicken Breast / Fillet', amount: '200 g', status: 'have'),
        RecipeIngredient(name: 'Garlic', amount: '3 cloves (minced)', status: 'have'),
        RecipeIngredient(name: 'Butter & Olive Oil', amount: '1 tbsp each', status: 'have'),
        RecipeIngredient(name: 'Milk / Cream', amount: '100 ml', status: 'have'),
        RecipeIngredient(name: 'Courgettes or Spinach', amount: '½ cup', status: 'have'),
        RecipeIngredient(name: 'Sea Salt & Cracked Black Pepper', amount: '½ tsp each', status: 'have'),
      ],
      cookingSteps: [
        'Season chicken with salt, pepper, and sear in a skillet with olive oil until golden on both sides (6-8 mins); set aside.',
        'In the same skillet, melt butter and sauté minced garlic and sliced courgettes for 2 minutes.',
        'Pour in milk/cream and simmer gently until sauce begins to thicken and emulsify.',
        'Return chicken to the pan, baste in the garlic herb sauce for 3 minutes, and serve hot.',
      ],
    ),
    Recipe(
      id: 'disc_5',
      title: 'Sichuan Dan Dan Spicy Peanut Noodles',
      koreanTitle: '사천 탄탄면',
      imageUrl: '',
      cookingTimeMinutes: 12,
      cookingMethod: 'Stovetop',
      difficulty: 'Easy',
      kitchenMatchPercent: 95,
      category: 'Sichuan Street',
      ingredients: [
        RecipeIngredient(name: 'Noodles / Meehun', amount: '1 portion', status: 'have'),
        RecipeIngredient(name: 'Lao Gan Ma Chili Crisp', amount: '1.5 tbsp', status: 'have'),
        RecipeIngredient(name: 'Soy Sauce', amount: '1 tbsp', status: 'have'),
        RecipeIngredient(name: 'Peanut Butter or Tahini', amount: '1 tbsp', status: 'have'),
        RecipeIngredient(name: 'Garlic', amount: '2 cloves (minced)', status: 'have'),
        RecipeIngredient(name: 'Rice Vinegar & Sesame Oil', amount: '1 tsp each', status: 'have'),
      ],
      cookingSteps: [
        'Boil noodles until chewy and springy; reserve 3 tbsp hot noodle cooking water.',
        'In a serving bowl, whisk Lao Gan Ma, soy sauce, peanut butter, minced garlic, rice vinegar, and sesame oil with the reserved noodle water until creamy.',
        'Drain noodles and drop directly into the spicy peanut sauce.',
        'Toss vigorously until every noodle strand is coated in glossy, fragrant chili sauce.',
      ],
    ),
    Recipe(
      id: 'disc_6',
      title: 'Spanish Gambas al Ajillo (Sizzling Garlic Prawns)',
      koreanTitle: '감바스 알 아히요',
      imageUrl: '',
      cookingTimeMinutes: 10,
      cookingMethod: 'Stovetop',
      difficulty: 'Easy',
      kitchenMatchPercent: 90,
      category: 'Spanish Tapas',
      ingredients: [
        RecipeIngredient(name: 'Prawns / Shrimp', amount: '8 pieces', status: 'have'),
        RecipeIngredient(name: 'Garlic', amount: '5 cloves (thinly sliced)', status: 'have'),
        RecipeIngredient(name: 'Cooking Oil or Olive Oil', amount: '3 tbsp', status: 'have'),
        RecipeIngredient(name: 'Butter', amount: '1 tbsp', status: 'have'),
        RecipeIngredient(name: 'Chili Flakes & Salt', amount: '½ tsp each', status: 'have'),
        RecipeIngredient(name: 'Crusty Bread or Toast', amount: '2 slices', status: 'have'),
      ],
      cookingSteps: [
        'Warm oil and butter in a shallow skillet over low-medium heat; add sliced garlic and chili flakes.',
        'Cook slowly for 2 minutes until garlic turns translucent and golden (do not burn).',
        'Add prawns seasoned with salt; cook 2 minutes until succulent and pink.',
        'Serve immediately while bubbling, dipping toasted crusty bread into the aromatic garlic oil.',
      ],
    ),
    Recipe(
      id: 'disc_7',
      title: 'Japanese Golden Curry Rice with Caramelized Onion',
      koreanTitle: '일본 골든 카레 라이스',
      imageUrl: '',
      cookingTimeMinutes: 20,
      cookingMethod: 'Stovetop',
      difficulty: 'Medium',
      kitchenMatchPercent: 92,
      category: 'Japanese Comfort',
      ingredients: [
        RecipeIngredient(name: 'Cooked Jasmine Rice', amount: '1 bowl', status: 'have'),
        RecipeIngredient(name: 'Potato or Carrot', amount: '1 medium', status: 'have'),
        RecipeIngredient(name: 'Curry Cube or Powder', amount: '1 cube (or 1 tbsp powder)', status: 'have'),
        RecipeIngredient(name: 'Butter & Soy Sauce', amount: '1 tsp each', status: 'have'),
        RecipeIngredient(name: 'Salt & Pepper', amount: '¼ tsp', status: 'have'),
      ],
      cookingSteps: [
        'Sauté diced potatoes and aromatics in butter with a pinch of salt until lightly browned.',
        'Add 350ml water, bring to a simmer, and cook 10 minutes until potatoes are fork-tender.',
        'Turn off heat, break in Japanese curry cube, and stir gently until completely dissolved.',
        'Simmer on low for 3 minutes until thick and glossy; ladle over steaming hot jasmine rice.',
      ],
    ),
    Recipe(
      id: 'disc_8',
      title: 'Double Dark Chocolate Molten Lava Mug Cake',
      koreanTitle: '초콜릿 머그 케이크',
      imageUrl: '',
      cookingTimeMinutes: 4,
      cookingMethod: 'Microwave',
      difficulty: 'Easy',
      kitchenMatchPercent: 95,
      category: 'Bake & Dessert',
      ingredients: [
        RecipeIngredient(name: 'All-Purpose Flour', amount: '3 tbsp', status: 'have'),
        RecipeIngredient(name: 'Sugar or Honey', amount: '2 tbsp', status: 'have'),
        RecipeIngredient(name: 'Cocoa Powder / Matcha', amount: '1 tbsp', status: 'have'),
        RecipeIngredient(name: 'Milk', amount: '3 tbsp', status: 'have'),
        RecipeIngredient(name: 'Melted Butter', amount: '1 tbsp', status: 'have'),
        RecipeIngredient(name: 'Chocolate Chip / Piece', amount: '1 chunk', status: 'have'),
      ],
      cookingSteps: [
        'In a ceramic coffee mug, whisk flour, sugar, cocoa powder, and a tiny pinch of salt.',
        'Stir in milk and melted butter until a smooth cake batter forms.',
        'Press a chocolate chunk right into the center of the batter.',
        'Microwave on high for 65–75 seconds. The edges should be set with a molten, gooey lava center.',
      ],
    ),
    Recipe(
      id: 'disc_9',
      title: 'Fluffy Strawberry Soufflé Pancake Cloud',
      koreanTitle: '딸기 수플레 팬케이크',
      imageUrl: '',
      cookingTimeMinutes: 18,
      cookingMethod: 'Stovetop',
      difficulty: 'Medium',
      kitchenMatchPercent: 90,
      category: 'Dessert & Pastry',
      ingredients: [
        RecipeIngredient(name: 'Eggs', amount: '2 large (separated)', status: 'have'),
        RecipeIngredient(name: 'Sugar', amount: '2 tbsp', status: 'have'),
        RecipeIngredient(name: 'Flour', amount: '2 tbsp', status: 'have'),
        RecipeIngredient(name: 'Milk', amount: '1 tbsp', status: 'have'),
        RecipeIngredient(name: 'Butter', amount: '1 tsp', status: 'have'),
        RecipeIngredient(name: 'Honey or Maple Syrup', amount: '1 tbsp', status: 'have'),
      ],
      cookingSteps: [
        'Whisk egg yolks, milk, and flour in a bowl until smooth.',
        'In a separate clean bowl, whip egg whites with sugar until stiff glossy meringue peaks form.',
        'Gently fold ⅓ of meringue into yolk mixture, then fold in remainder without deflating.',
        'Melt butter in a pan on lowest heat, scoop tall batter mounds, add 1 tsp water, cover, and steam 4 mins each side.',
      ],
    ),
    Recipe(
      id: 'disc_10',
      title: 'French Onion Gruyère Toasted Baguette',
      koreanTitle: '어니언 치즈 토스트',
      imageUrl: '',
      cookingTimeMinutes: 12,
      cookingMethod: 'Air Fryer',
      difficulty: 'Easy',
      kitchenMatchPercent: 92,
      category: 'Cafe Comfort',
      ingredients: [
        RecipeIngredient(name: 'Bread or Baguette', amount: '2 thick slices', status: 'have'),
        RecipeIngredient(name: 'Red Cheddar or Gruyère', amount: '50 g', status: 'have'),
        RecipeIngredient(name: 'Butter', amount: '1.5 tbsp', status: 'have'),
        RecipeIngredient(name: 'Garlic', amount: '1 clove', status: 'have'),
        RecipeIngredient(name: 'Black Pepper & Thyme', amount: '1 pinch', status: 'have'),
      ],
      cookingSteps: [
        'Rub bread lightly with cut garlic clove and spread softened butter on both sides.',
        'Layer generously with grated sharp cheddar or cheese and a pinch of black pepper.',
        'Air fry at 190°C (375°F) for 5-6 minutes until cheese forms golden, caramelized blistering edges.',
        'Slice diagonally and enjoy while crunchy and molten.',
      ],
    ),
    Recipe(
      id: 'disc_11',
      title: 'Spicy Korean Rose Cream Rigatoni',
      koreanTitle: '로제 파스타',
      imageUrl: '',
      cookingTimeMinutes: 15,
      cookingMethod: 'Stovetop',
      difficulty: 'Easy',
      kitchenMatchPercent: 95,
      category: 'Fusion',
      ingredients: [
        RecipeIngredient(name: 'Noodles or Pasta', amount: '1 portion', status: 'have'),
        RecipeIngredient(name: 'Gochujang Paste', amount: '1 tbsp', status: 'have'),
        RecipeIngredient(name: 'Milk or Cream', amount: '100 ml', status: 'have'),
        RecipeIngredient(name: 'Butter & Garlic', amount: '1 tbsp & 2 cloves', status: 'have'),
        RecipeIngredient(name: 'Irish Ham or Bacon', amount: '40 g', status: 'have'),
        RecipeIngredient(name: 'Salt & Black Pepper', amount: '¼ tsp each', status: 'have'),
      ],
      cookingSteps: [
        'Cook pasta in salted boiling water until al dente.',
        'Melt butter with minced garlic in a pan, sauté sliced ham until slightly browned.',
        'Stir in gochujang paste and pour in milk/cream; simmer 2 minutes into a velvety pink Rose sauce.',
        'Toss pasta in the creamy sauce, season with black pepper, and finish with grated cheese.',
      ],
    ),
    Recipe(
      id: 'disc_12',
      title: 'Cinnamon Sugar Crisp Churro Toast',
      koreanTitle: '시나몬 츄러스 토스트',
      imageUrl: '',
      cookingTimeMinutes: 6,
      cookingMethod: 'Air Fryer',
      difficulty: 'Easy',
      kitchenMatchPercent: 100,
      category: 'Bake & Dessert',
      ingredients: [
        RecipeIngredient(name: 'Bread', amount: '2 slices', status: 'have'),
        RecipeIngredient(name: 'Butter', amount: '2 tbsp (melted)', status: 'have'),
        RecipeIngredient(name: 'Sugar', amount: '1.5 tbsp', status: 'have'),
        RecipeIngredient(name: 'Ground Cinnamon', amount: '½ tsp', status: 'have'),
      ],
      cookingSteps: [
        'Mix granulated sugar and ground cinnamon in a shallow bowl.',
        'Cut bread slices into 1-inch fingers or batons.',
        'Brush all sides generously with melted butter, then dredge thoroughly in the cinnamon sugar mixture.',
        'Air fry at 180°C (350°F) for 5 minutes until crispy on the outside with a warm, soft center.',
      ],
    ),
    Recipe(
      id: 'disc_13',
      title: 'Thai Holy Basil Savory Minced Pork Bowl (Pad Krapow)',
      koreanTitle: '태국식 바질 돼지고기 덮밥',
      imageUrl: '',
      cookingTimeMinutes: 12,
      cookingMethod: 'Stovetop',
      difficulty: 'Medium',
      kitchenMatchPercent: 92,
      category: 'Southeast Asian',
      ingredients: [
        RecipeIngredient(name: 'Pork Chop / Minced Pork', amount: '150 g (finely chopped)', status: 'have'),
        RecipeIngredient(name: 'Garlic & Chili', amount: '3 cloves & 1 red chili', status: 'have'),
        RecipeIngredient(name: 'Soy Sauce & Fish Sauce', amount: '1 tbsp each', status: 'have'),
        RecipeIngredient(name: 'Cooking Oil', amount: '1 tbsp', status: 'have'),
        RecipeIngredient(name: 'Cooked Jasmine Rice', amount: '1 bowl', status: 'have'),
        RecipeIngredient(name: 'Egg', amount: '1 (crispy fried)', status: 'have'),
      ],
      cookingSteps: [
        'Pound garlic and chili in a mortar or mince finely.',
        'Heat oil in a hot skillet/wok; fry garlic and chili until fragrant (30 seconds).',
        'Add chopped pork, breaking it apart, and stir-fry on high heat with soy sauce and a splash of water until seared.',
        'Serve piping hot over jasmine rice topped with a crispy-edged fried egg.',
      ],
    ),
    Recipe(
      id: 'disc_14',
      title: 'Mediterranean Lemon Herb Feta Salad',
      koreanTitle: '지중해식 페타 샐러드',
      imageUrl: '',
      cookingTimeMinutes: 8,
      cookingMethod: 'No-cook',
      difficulty: 'Easy',
      kitchenMatchPercent: 90,
      category: 'Healthy Bistro',
      ingredients: [
        RecipeIngredient(name: 'Irish Courgettes or Cucumber', amount: '1 medium', status: 'have'),
        RecipeIngredient(name: 'Cheddar or Feta Cheese', amount: '40 g', status: 'have'),
        RecipeIngredient(name: 'Olive Oil or Butter', amount: '1.5 tbsp', status: 'have'),
        RecipeIngredient(name: 'Fresh Lemon Juice', amount: '1 tbsp', status: 'have'),
        RecipeIngredient(name: 'Sea Salt & Dried Oregano', amount: '½ tsp each', status: 'have'),
      ],
      cookingSteps: [
        'Thinly slice courgettes or cucumbers into delicate ribbons using a peeler.',
        'Whisk olive oil, fresh lemon juice, sea salt, and oregano in a bowl until an emulsified dressing forms.',
        'Toss vegetable ribbons gently in the citrus herb dressing.',
        'Top with crumbled cheese and cracked black pepper for a refreshing, crisp plate.',
      ],
    ),
    Recipe(
      id: 'disc_15',
      title: 'Crispy Rosemary Garlic Roasted Hasselback Potatoes',
      koreanTitle: '로즈마리 갈릭 아코디언 감자',
      imageUrl: '',
      cookingTimeMinutes: 22,
      cookingMethod: 'Air Fryer',
      difficulty: 'Easy',
      kitchenMatchPercent: 95,
      category: 'Bistro Side',
      ingredients: [
        RecipeIngredient(name: 'Potatoes', amount: '2 medium', status: 'have'),
        RecipeIngredient(name: 'Butter (melted)', amount: '2 tbsp', status: 'have'),
        RecipeIngredient(name: 'Garlic', amount: '2 cloves (crushed)', status: 'have'),
        RecipeIngredient(name: 'Rosemary / Herbs', amount: '1 sprig', status: 'have'),
        RecipeIngredient(name: 'Sea Salt & Cracked Black Pepper', amount: '½ tsp each', status: 'have'),
      ],
      cookingSteps: [
        'Place potato between two chopsticks; make thin vertical slices 2mm apart without cutting completely through.',
        'Whisk melted butter with crushed garlic, finely chopped rosemary, sea salt, and black pepper.',
        'Generously brush the garlic herb butter between every potato fan slice.',
        'Air fry at 195°C (385°F) for 18-20 minutes until the edges are shatteringly crisp and the interior is buttery soft.',
      ],
    ),
    Recipe(
      id: 'disc_16',
      title: 'Chewy Brown Butter Sea Salt Chocolate Chunk Cookies',
      koreanTitle: '수제 초코칩 쿠키',
      imageUrl: '',
      cookingTimeMinutes: 20,
      cookingMethod: 'Air Fryer',
      difficulty: 'Medium',
      kitchenMatchPercent: 92,
      category: 'Bake & Dessert',
      ingredients: [
        RecipeIngredient(name: 'All-Purpose Flour', amount: '1 cup', status: 'have'),
        RecipeIngredient(name: 'Butter', amount: '½ cup (browned)', status: 'have'),
        RecipeIngredient(name: 'Sugar (Brown & White)', amount: '½ cup combined', status: 'have'),
        RecipeIngredient(name: 'Egg Yolk', amount: '1 large', status: 'have'),
        RecipeIngredient(name: 'Chocolate Chips / Chunks', amount: '½ cup', status: 'have'),
        RecipeIngredient(name: 'Flaky Sea Salt', amount: '1 pinch', status: 'have'),
      ],
      cookingSteps: [
        'Melt butter in a pan until foamy and nutty brown specks appear; let cool slightly.',
        'Whisk browned butter with sugars, egg yolk, and a pinch of salt until glossy.',
        'Fold in flour and chocolate chunks until dough comes together.',
        'Scoop dough balls onto parchment; bake or air fry at 170°C (340°F) for 9 minutes. Sprinkle flaky sea salt immediately.',
      ],
    ),
  ];

  static const List<FridgeItem> seedFridgeItems = [
    FridgeItem(
      id: 'f1',
      name: 'Aged Kimchi',
      location: StorageLocation.fridge,
      quantityMode: QuantityMode.approximate,
      quantityDisplay: 'Plenty',
      status: 'Have',
    ),
    FridgeItem(
      id: 'f2',
      name: 'Milk',
      location: StorageLocation.fridge,
      quantityMode: QuantityMode.exact,
      quantityDisplay: '500 ml',
      status: 'Have',
    ),
    FridgeItem(
      id: 'f3',
      name: 'Firm Tofu',
      location: StorageLocation.fridge,
      quantityMode: QuantityMode.exact,
      quantityDisplay: '1 pack (300g)',
      status: 'Have',
    ),
    FridgeItem(
      id: 'f4',
      name: 'Frozen Dumplings',
      location: StorageLocation.freezer,
      quantityMode: QuantityMode.approximate,
      quantityDisplay: 'Some',
      status: 'Have',
    ),
    FridgeItem(
      id: 'f5',
      name: 'Jasmine Rice',
      location: StorageLocation.pantry,
      quantityMode: QuantityMode.approximate,
      quantityDisplay: 'Plenty',
      status: 'Have',
    ),
    FridgeItem(
      id: 'f6',
      name: 'Gochujang Paste',
      location: StorageLocation.pantry,
      quantityMode: QuantityMode.approximate,
      quantityDisplay: 'Almost empty',
      status: 'Running low',
    ),
  ];
}
